name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'  # reagiert auf Tags wie v0.1, v1.0.0, v2.3.4 etc.


permissions:
  contents: write  # <- Wichtig! Gibt dem Token Schreibrechte für Releases


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🆕 Automatisches Release für `${{ github.ref_name }}`
            Änderungen: [CHANGELOG.md](https://github.com/lordrasmus/pi-backup/blob/main/CHANGELOG.md)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
